# Generated by Django 3.0.6 on 2020-05-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ip_address',
            field=models.CharField(default='1.1.1.1', max_length=30),
        ),
    ]
