# Generated by Django 3.0.4 on 2020-05-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.URLField(),
        ),
    ]
