# Generated by Django 3.0.4 on 2020-05-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200515_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
